### ISSUE TITLE
Support multiplication pattern

### ISSUE THREAD

**Issue by psyycker** [nickysemenza/ingredient-parser#26]
Hey,
Great work! 
I could spot that you are not supporting this kind of format:

`2 x 400g cans chickpeas, drained but not rinsed`

I have as a result `x`

Is it something you'd support?

**Comment by nickysemenza** [comment]
Oh that's an interesting idea, and certainly seems to be something that should be supported. I think i've come across some cases where the format doesn't have the `x` even (such as `2  400g cans`).

Would you expect the output in this case to be:
```
Ingredient{
	name: "400g cans chickpeas", 
	amounts: [Amount{unit: "whole", value: 2.0}],
	modifier: "drained but not rinsed"

```

**Comment by remyvillulles** [comment]
I'm not sure that the name would be correct, I think we'd expect maybe just "cans chickpeas"? How are you parsing `400g cans chickpeas` at the moment?

**Comment by psyycker** [comment]
I'm not sure that the name would be correct, I think we'd expect maybe just "cans chickpeas"? How are you parsing 400g cans chickpeas at the moment?

**Comment by nickysemenza** [comment]
This will be parsed as 
```
{
  "name": "cans chickpeas",
  "amounts": [
    {
      "unit": "Gram",
      "value": 800,
      "upper_value": null
    }
  ],
  "modifier": "drained but not rinsed"
}
```
now
